# Veri seti ve model kaydedilecek yollar:
data: data/                        # Eğitim ve doğrulama veri setinin yolu
save_model: models/model.ot-tr     # Eğitilen modelin kaydedileceği yer
save_checkpoint_steps: 10000       # Her bu kadar adımda bir model kontrol noktası kaydedilir
keep_checkpoint: 10                # Kaç adet model kontrol noktasının saklanacağı
seed: 3435                         # Rastgelelik için tohum değeri

# Eğitim ayarları:
train_steps: 500000                # Toplam eğitim adım sayısı
valid_steps: 10000                 # Her bu kadar adımda bir doğrulama yapılır
warmup_steps: 8000                 # Isınma adımları (örneğin, öğrenme hızını artırma süreci)
report_every: 100                   # Her bu kadar adımda bir rapor alınır

# Model yapılandırması:
decoder_type: transformer           # Çözümleyici tipi (örneğin, transformer, rnn)
encoder_type: transformer           # Kodlayıcı tipi (örneğin, transformer, rnn)
word_vec_size: 512                  # Kelime vektör boyutu
hidden_size: 512                     # Gizli katman boyutu
layers: 6                            # Toplam katman sayısı
transformer_ff: 2048                # Transformer iç katman boyutu
heads: 8                            # Multi-Head dikkat başlığı sayısı

# Optimizasyon ayarları:
accum_count: 8                      # Birden fazla gradient akkümülasyonu (hafif büyütme)
optim: adam                         # Kullanılacak optimizer (örneğin, adam, sgd)
adam_beta1: 0.9                      # Adam optimizer beta1 değeri
adam_beta2: 0.998                    # Adam optimizer beta2 değeri
decay_method: noam                  # Azalma yöntemi (örneğin, noam, standard)
learning_rate: 2.0                  # Başlangıç öğrenme hızı
max_grad_norm: 0.0                  # Maksimum gradyan normu (gradyan clipping için)

# Topluluk (batch) ayarları:
batch_size: 4096                    # Topluluk boyutu (batch size)
batch_type: tokens                   # Topluluk tipi (örneğin, tokens, sents)
normalization: tokens               # Normalizasyon tipi (örneğin, tokens, sents)
dropout: 0.1                         # Dropout oranı
label_smoothing: 0.1                # Etiket yumuşatma (label smoothing) oranı

# Diğer model ayarları:
param_init: 0.0                      # Parametre başlangıç değeri
param_init_glorot: 'true'           # Glorot tipi parametre başlangıç değeri
position_encoding: 'true'           # Pozisyon kodlamasını (position encoding) kullan
